### ISSUE TITLE
broken gpg support for debian repos

### ISSUE THREAD

**Issue by alfredodeza** [alfredodeza/merfi#26]
this should never happen:

    $ merfi gpg
    --> Starting path collection, looking for files to sign
    Traceback (most recent call last):
      File "/home/ubuntu/.virtualenvs/merfi/bin/merfi", line 10, in <module>
        execfile(__file__)
      File "/home/ubuntu/python/merfi/bin/merfi", line 6, in <module>
        main.Merfi()
      File "/home/ubuntu/python/merfi/merfi/main.py", line 38, in __init__
        self.main(argv)
      File "/home/ubuntu/python/merfi/merfi/decorators.py", line 45, in newfunc
        return f(*a, **kw)
      File "/home/ubuntu/python/merfi/merfi/main.py", line 60, in main
        parser.dispatch()
      File "/home/ubuntu/.virtualenvs/merfi/local/lib/python2.7/site-packages/tambo-0.2.0-py2.7.egg/tambo/dispatcher.py", line 22, in dispatch
        return instance.parse_args()
      File "/home/ubuntu/python/merfi/merfi/backends/base.py", line 16, in parse_args
        self.sign()
      File "/home/ubuntu/python/merfi/merfi/backends/gpg.py", line 36, in sign
        repo_paths = RepoCollector.debian_release_files(repo)
      File "/home/ubuntu/python/merfi/merfi/collector.py", line 69, in debian_release_files
        root, dirs, files = next(walk(dists))
    StopIteration

It also seems like I need to be in a specific directory for this to work, which should never be the case. There is no need to call `next` either, one can just loop over the iterator here.

**Comment by alfredodeza** [comment]
Fixed with a8e3214cbd36232d983374927d382472aae69f02
